// Top 3 trending movies for each brand
// Replace the Supabase URLs with your actual uploaded images and videos

const trendingMovies = {
  starWars: [
    {
      id: 'cat-sw-1',
      title: 'The MandaLorian',
      name: 'The MandaLorian',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/MandaLorian.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/star-wars-1.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/MandaLorian-vid.mp4',
      overview: 'This is the way... to the food bowl.',
      vote_average: 9.8,
      release_date: '2026-01-21',
      runtime: 30,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Aventura' }],
    },
    {
      id: 'cat-sw-2',
      title: 'Return of the Jedi Cats',
      name: 'Return of the Jedi Cats',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/starwars-1.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/star-wars-2.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/star-wars-2-vid.mp4',
      overview: 'A long time ago in a living room far, far away...',
      vote_average: 9.5,
      release_date: '2026-01-21',
      runtime: 28,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Aventura' }],
    },
    {
      id: 'cat-sw-3',
      title: 'The Paw-ce Awakens',
      name: 'The Paw-ce Awakens',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/star-wars-2.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/star-wars-3.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/star-wars-3.mp4',
      overview: 'The force is strong with this feline.',
      vote_average: 9.7,
      release_date: '2026-01-21',
      runtime: 32,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Aventura' }],
    },
  ],

  disney: [
    {
      id: 'cat-disney-1',
      title: 'The Lion King: Circle of Naps',
      name: 'The Lion King: Circle of Naps',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/LionKing.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/disney-1.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/disney-1.mp4',
      overview: 'Everything the light touches is my kingdom... and my nap spot.',
      vote_average: 9.9,
      release_date: '2026-01-21',
      runtime: 88,
      genres: [{ id: 1, name: 'Animación' }, { id: 2, name: 'Aventura' }],
    },
    {
      id: 'cat-disney-2',
      title: 'Catatouille',
      name: 'Catatouille',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/catatuile.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/disney-2.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/disney-2.mp4',
      overview: 'Anyone can cook, but only cats can nap on the counter.',
      vote_average: 9.6,
      release_date: '2026-01-21',
      runtime: 92,
      genres: [{ id: 1, name: 'Animación' }, { id: 2, name: 'Comedia' }],
    },
    {
      id: 'cat-disney-3',
      title: 'Toy Story: Los Gatos de Andy',
      name: 'Toy Story: Los Gatos de Andy',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/toyStory.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/disney-3.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/disney-3.mp4',
      overview: "You've got a friend in meow.",
      vote_average: 9.4,
      release_date: '2026-01-21',
      runtime: 81,
      genres: [{ id: 1, name: 'Animación' }, { id: 2, name: 'Familia' }],
    },
  ],

  pixar: [
    {
      id: 'cat-pixar-1',
      title: 'Toy Story: Laser Pointer Chronicles',
      name: 'Toy Story: Laser Pointer Chronicles',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/toyStory.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/pixar-1.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/pixar-1.mp4',
      overview: 'To infinity... and the top of the fridge!',
      vote_average: 9.8,
      release_date: '2026-01-21',
      runtime: 95,
      genres: [{ id: 1, name: 'Animación' }, { id: 2, name: 'Familia' }],
    },
    {
      id: 'cat-pixar-2',
      title: 'Finding Nemo: Lost in the Litter',
      name: 'Finding Nemo: Lost in the Litter',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/nemo.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/pixar-2.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/pixar-2.mp4',
      overview: 'Just keep scratching, just keep scratching.',
      vote_average: 9.5,
      release_date: '2026-01-21',
      runtime: 100,
      genres: [{ id: 1, name: 'Animación' }, { id: 2, name: 'Aventura' }],
    },
    {
      id: 'cat-pixar-3',
      title: 'WALL-E and the Cardboard Kingdom',
      name: 'WALL-E and the Cardboard Kingdom',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/WALLE.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/pixar-3.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/pixar-3.mp4',
      overview: 'One robot, one cat, infinite boxes.',
      vote_average: 9.7,
      release_date: '2026-01-21',
      runtime: 98,
      genres: [{ id: 1, name: 'Animación' }, { id: 2, name: 'Ciencia ficción' }],
    },
  ],

  marvel: [
    {
      id: 'cat-marvel-1',
      title: 'The Avengers: Infinity Paws',
      name: 'The Avengers: Infinity Paws',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/marvel-1.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/marvel-1.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/super-1.mp4',
      overview: 'Two super cats unite against their greatest nemesis. The fate of the universe hangs in the balance.',
      vote_average: 9.9,
      release_date: '2026-01-21',
      runtime: 161,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Aventura' }],
    },
    {
      id: 'cat-marvel-2',
      title: 'Thor Ragnarok',
      name: 'Thor Ragnarok',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/thor.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/marvel-2.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/marvel-2.mp4',
      overview: 'Size of a cat, heart of a lion, brain of a potato.',
      vote_average: 9.3,
      release_date: '2026-01-21',
      runtime: 118,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Comedia' }],
    },
    {
      id: 'cat-marvel-3',
      title: "Guardians of the Galaxy: Rocket's Cousin",
      name: "Guardians of the Galaxy: Rocket's Cousin",
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/posters/marvel-3.jpg',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/marvel-3.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/marvel-3.mp4',
      overview: "Ain't no thing like me, except me.",
      vote_average: 9.6,
      release_date: '2026-01-21',
      runtime: 150,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Ciencia ficción' }],
    },
  ],

  nationalGeographic: [
    {
      id: 'cat-geo-1',
      title: 'Wild Cats: Domestic Edition',
      name: 'Wild Cats: Domestic Edition',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/posters/geo-1.jpg',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/geo-1.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/geo-1.mp4',
      overview: 'Witness the apex predator of the living room.',
      vote_average: 9.7,
      release_date: '2026-01-21',
      runtime: 52,
      genres: [{ id: 1, name: 'Documental' }, { id: 2, name: 'Naturaleza' }],
    },
    {
      id: 'cat-geo-2',
      title: 'Planet Earth: The House Cat',
      name: 'Planet Earth: The House Cat',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/posters/geo-2.jpg',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/geo-2.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/geo-2.mp4',
      overview: 'Narrated by David Attenborough (in your dreams).',
      vote_average: 9.8,
      release_date: '2026-01-21',
      runtime: 48,
      genres: [{ id: 1, name: 'Documental' }, { id: 2, name: 'Naturaleza' }],
    },
    {
      id: 'cat-geo-3',
      title: 'The Secret Life of House Cats',
      name: 'The Secret Life of House Cats',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/posters/geo-3.jpg',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/geo-3.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/geo-3.mp4',
      overview: 'What do they do when you leave? Everything.',
      vote_average: 9.9,
      release_date: '2026-01-21',
      runtime: 55,
      genres: [{ id: 1, name: 'Documental' }, { id: 2, name: 'Naturaleza' }],
    },
  ],

  star: [
    {
      id: 'cat-star-1',
      title: 'Caxter',
      name: 'Caxter',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/caxter.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/star-1.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/caxter-vid.mp4',
      overview: "Tonight's the night. And it's going to happen again and again.",
      vote_average: 9.4,
      release_date: '2026-01-21',
      runtime: 45,
      genres: [{ id: 1, name: 'Crimen' }, { id: 2, name: 'Drama' }],
    },
    {
      id: 'cat-star-2',
      title: 'cAtVATAR',
      name: 'cAtVATAR',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/CATVATAR.png',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/star-2.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/cats/star-2.mp4',
      overview: 'In the depths of the ocean, a cat discovers a whole new world beneath the waves.',
      vote_average: 9.2,
      release_date: '2026-01-21',
      runtime: 162,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Aventura' }],
    },
    {
      id: 'cat-star-3',
      title: 'Mandarinator',
      name: 'Mandarinator',
      poster_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/mandarinator.jpg',
      backdrop_path: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/backdrops/star-3.jpg',
      video_url: 'https://krhtrpwyzjpqnmxailto.supabase.co/storage/v1/object/public/brand-videos/mandarinator.mp4',
      overview: "I'll be back... for more treats.",
      vote_average: 9.5,
      release_date: '2026-01-21',
      runtime: 107,
      genres: [{ id: 1, name: 'Acción' }, { id: 2, name: 'Ciencia ficción' }],
    },
  ],
};

export default trendingMovies;
